spring:
  application:
    name: module-infra
  sql:
    init:
      platform: mysql
      mode: embedded  # schema.sql 실행 활성화
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/theater
    username: user
    password: password

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
