services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_USER=user
      - MYSQL_DATABASE=theater
      - MYSQL_PASSWORD=password
      - TZ=Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:7.4.2-alpine
    container_name: simple-redis
    ports:
      - "6379:6379"
    command: [ "redis-server" ]

volumes:
  mysql-data:

